import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    username:{
        type:String,
        required:true,
        unique:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    profilePic:{
        type:String,
        default:"https://via.placeholder.com/150x150/1DA1F2/FFFFFF?text=U"
    },
    coverPic:{
        type:String,
        default:""
    },
    bio:{
        type:String,
        default:""
    },
    location:{
        type:String,
        default:""
    },
    website:{
        type:String,
        default:""
    },
    verified:{
        type:Boolean,
        default:false
    },
    followers:{
        type:Array,
        default:[]
    },
    following:{
        type:Array,
        default:[]
    }, 
    bookmarks:{
        type:Array,
        default:[]
    }
},{timestamps:true});

export const User = mongoose.model("User", userSchema);